# login post data for logging in
def login_request(token, state):
    return {

    "reseller":	"",
    "CSRF_TOKEN":	token,
    "loginForm:storeId":	"removed",
    "loginForm:userId":	"removed",
    "loginForm:password":	"removed",
    "org.apache.myfaces.trinidad.faces.FORM": "loginForm",
    "_noJavaScript":	"false",
    "javax.faces.ViewState": state,
    "source":	"loginForm:login"

    }

# form post data to get cc link
def form_post_request(token,view, expiry, order_number, subtotal, deliver_amount, total, currency,year,name1,name2,address1,address2,
city,province,country,post_code,phone,fax,email,comment):
    
    return {
  "CSRF_TOKEN": token,
  "status": "order",
  "hiddenTransactionType": "sale",
  "hiddenHighRiskTransactionType": "sale",
  "subsequentTransactionCurrency": "",
  "isBaiFieldTobeDisplayed": "false",
  "isSenderInfoTobeDisplayedVisa": "false",
  "isSenderInfoTobeDisplayedMasterCardMaestro": "false",
  "isPurposeOfPaymentToBeDisplayed": "false",
  "isTtiFieldTobeDisplayed": "false",
  "isPaymentURLOnly": "true",
  "paymentURLRecurringAllowed": "false",
  "isServiceLocationInfoTobeDisplayed": "true",
  "isMfriFieldToBeDisplayed": "false",
  "isReceiverInfoToBeDisplayed": "false",
  "orderDataForm:paymentForms:1:j_idt168": "true",
  "orderDataForm:paymentForms:1:paymentFields:0:paymentFieldComponentCheckboxPaymentUrl": "on",
  "orderDataForm:paymentForms:1:paymentFields:1:subPaymentFields:0:paymentFieldComponentText": expiry,
  "orderDataForm:paymentForms:1:paymentFields:1:subPaymentFields:1:paymentFieldComponentText": "23:59:59",
  "orderDataForm:paymentForms:1:paymentFields:2:paymentFieldComponentText": order_number,
  "orderDataForm:paymentForms:1:paymentFields:3:paymentFieldComponentText": "",
  "orderDataForm:paymentForms:1:paymentFields:4:paymentFieldComponentText": order_number,
  "orderDataForm:paymentForms:1:paymentFields:5:paymentFieldComponentText": subtotal,
  "orderDataForm:paymentForms:1:paymentFields:6:paymentFieldComponentText": deliver_amount,
  "orderDataForm:paymentForms:1:paymentFields:7:paymentFieldComponentText": "",
  "orderDataForm:paymentForms:1:paymentFields:8:paymentFieldComponentText": total,
  "orderDataForm:paymentForms:1:paymentFields:9:paymentFieldComponentSelect": currency,
  "orderDataForm:paymentForms:1:paymentFields:11:paymentFieldComponentText": "",
  "orderDataForm:paymentForms:1:paymentFields:12:paymentFieldComponentText": "",
  "orderDataForm:paymentForms:1:paymentFields:13:paymentFieldComponentText": "",
  "orderDataForm:paymentForms:1:paymentFields:14:paymentFieldComponentText": "",
  "orderDataForm:paymentForms:1:paymentFields:15:paymentFieldComponentText": "",
  "orderDataForm:paymentForms:1:paymentFields:16:paymentFieldComponentText": "",
  "orderDataForm:paymentForms:2:j_idt168": "true",
  "orderDataForm:paymentForms:2:paymentFields:0:paymentFieldComponentSelect": "",
  "orderDataForm:paymentForms:2:paymentFields:1:paymentFieldComponentSelect": "null",
  "orderDataForm:paymentForms:2:paymentFields:2:paymentFieldComponentSelect": "sale",
  "orderDataForm:paymentForms:2:paymentFields:4:paymentFieldComponentText": "",
  "orderDataForm:paymentForms:2:paymentFields:5:subPaymentFields:0:paymentFieldComponentSelect": "01",
  "orderDataForm:paymentForms:2:paymentFields:5:subPaymentFields:1:paymentFieldComponentSelect": year,
  "orderDataForm:paymentForms:2:paymentFields:6:paymentFieldComponentText": "",
  "orderDataForm:paymentForms:2:paymentFields:8:paymentFieldComponentSelect": "null",
  "orderDataForm:paymentForms:3:j_idt168": "false",
  "orderDataForm:paymentForms:3:paymentFields:0:paymentFieldComponentText": order_number,
  "orderDataForm:paymentForms:3:paymentFields:1:paymentFieldComponentText": name1,
  "orderDataForm:paymentForms:3:paymentFields:2:paymentFieldComponentText": name2,
  "orderDataForm:paymentForms:3:paymentFields:3:paymentFieldComponentText": address1,
  "orderDataForm:paymentForms:3:paymentFields:4:paymentFieldComponentText": address2,
  "orderDataForm:paymentForms:3:paymentFields:5:paymentFieldComponentText": city,
  "orderDataForm:paymentForms:3:paymentFields:6:paymentFieldComponentText": province,
  "orderDataForm:paymentForms:3:paymentFields:7:paymentFieldComponentSelectSorted": country,
  "orderDataForm:paymentForms:3:paymentFields:8:paymentFieldComponentText": post_code,
  "orderDataForm:paymentForms:3:paymentFields:9:paymentFieldComponentText": phone,
  "orderDataForm:paymentForms:3:paymentFields:10:paymentFieldComponentText": fax,
  "orderDataForm:paymentForms:3:paymentFields:11:paymentFieldComponentText": email,
  "orderDataForm:paymentForms:3:paymentFields:12:paymentFieldComponentSelect": "en_GB",
  "orderDataForm:paymentForms:3:paymentFields:13:paymentFieldComponentCheckboxCopyBillingToShipping": "on",
  "orderDataForm:paymentForms:4:j_idt168": "false",
  "orderDataForm:paymentForms:4:paymentFields:0:paymentFieldComponentText": name1,
  "orderDataForm:paymentForms:4:paymentFields:1:paymentFieldComponentText": address1,
  "orderDataForm:paymentForms:4:paymentFields:2:paymentFieldComponentText": address2,
  "orderDataForm:paymentForms:4:paymentFields:3:paymentFieldComponentText": city,
  "orderDataForm:paymentForms:4:paymentFields:4:paymentFieldComponentText": province,
  "orderDataForm:paymentForms:4:paymentFields:5:paymentFieldComponentSelectSorted": country,
  "orderDataForm:paymentForms:4:paymentFields:6:paymentFieldComponentText": post_code,
  "orderDataForm:paymentForms:4:paymentFields:7:paymentFieldComponentText": phone,
  "orderDataForm:paymentForms:5:j_idt168": "false",
  "orderDataForm:paymentForms:5:paymentFields:0:paymentFieldComponentText": "",
  "orderDataForm:paymentForms:5:paymentFields:1:paymentFieldComponentText": "",
  "orderDataForm:paymentForms:5:paymentFields:2:paymentFieldComponentText": "",
  "orderDataForm:paymentForms:5:paymentFields:3:paymentFieldComponentSelect": "",
  "orderDataForm:paymentForms:6:j_idt168": "false",
  "orderDataForm:paymentForms:6:paymentFields:0:paymentFieldComponentTextarea": comment,
  "org.apache.myfaces.trinidad.faces.FORM": "orderDataForm",
  "_noJavaScript": "false",
  "source": "orderDataForm:showConfirmation",
  "javax.faces.ViewState": view
}

# confirms submission of post data to form
def confirm_post_request(token, view):
  return {
	"CSRF_TOKEN": token,
	"status": "confirm",
	"org.apache.myfaces.trinidad.faces.FORM": "confirmOrderForm",
	"_noJavaScript": "false",
	"javax.faces.ViewState": view,
	"source": "confirmOrderForm:processOrderData"
}
